camel:
  springboot:
    name: Conduit Backend Camel implementation
    sourceLocationEnabled: true

  servlet:
    mapping:
      contextPath: /api/*


management:
  endpoints:
    web:
      exposure:
        include: "*"
