camel:
  springboot:
    name: Conduit Backend Camel implementation
    sourceLocationEnabled: true

  servlet:
    mapping:
      contextPath: /api/*

spring:

  datasource:
    url: jdbc:h2:file:./target/conduit.h2;AUTO_SERVER=TRUE

  jpa:
    database: h2
    hibernate:
      ddl-auto: update



management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    com:
      github:
        jacekszymanski: TRACE
