camel:
  springboot:
    name: Conduit Backend Camel implementation
    startup-summary-level: verbose
    dump-routes: true

    routes-include-pattern: classpath:camel/*.xml
    routes-reload-directory: src/main/resources/camel
    routes-reload-enabled: true
    routes-reload-pattern: "*.xml"
    routes-reload-remove-all-routes: false

  servlet:
    mapping:
      contextPath: /api/*

spring:

  datasource:
    url: jdbc:h2:file:./target/conduit.h2;AUTO_SERVER=TRUE

  jpa:
    database: h2
    hibernate:
      ddl-auto: update



management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    com:
      github:
        jacekszymanski: TRACE
